spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/diploma-project
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
    data:
      rest:
        basePath: /api
server:
  port: 5000